//
//  City.swift
//  KindergartenApp
//
//  Created by 김도훈 on 2023/10/04.
//

import Foundation

// enum을 배열처럼 사용(CaseIterable)
enum Sido: String, CaseIterable {
    case none = "시/도"
    case seoul = "서울특별시"
    case busan = "부산광역시"
    case daegu = "대구광역시"
    case incheon = "인천광역시"
    case gwangju = "광주광역시"
    case daejeon = "대전광역시"
    case ulsan = "울산광역시"
    case sejong = "세종특별자치시"
    case gyeonggi = "경기도"
    case gangwon = "강원특별자치도"
    case chungbuk = "충청북도"
    case chungnam = "충청남도"
    case jeonbuk = "전라북도"
    case jeonnam = "전라남도"
    case gyeongbuk = "경상북도"
    case gyeongnam = "경상남도"
    case jeju = "제주특별자치도"
}

enum Seoul: String, CaseIterable {
    case none = "시/군/구"
    case gangnam = "강남구"
    case gangdong = "강동구"
    case gangbuk = "강북구"
    case gangseo = "강서구"
    case gwanak = "관악구"
    case gwangjin = "광진구"
    case guro = "구로구"
    case geumcheon = "금천구"
    case nowon = "노원구"
    case dobong = "도봉구"
    case dongdaemun = "동대문구"
    case dongjak = "동작구"
    case mapo = "마포구"
    case seodaemun = "서대문구"
    case seocho = "서초구"
    case seongdong = "성동구"
    case seongbuk = "성북구"
    case songpa = "송파구"
    case yangcheon = "양천구"
    case yeongdeungpo = "영등포구"
    case yongsan = "용산구"
    case eunpyeong = "은평구"
    case jongno = "종로구"
    case jung = "중구"
    case jungrang = "중랑구"
}

enum Busan: String, CaseIterable {
    case none = "시/군/구"
    case gangseo = "강서구"
    case geumjeong = "금정구"
    case gijang = "기장군"
    case namgu = "남구"
    case donggu = "동구"
    case dongnae = "동래구"
    case busanjin = "부산진구"
    case bukgu = "북구"
    case sasang = "사상구"
    case saha = "사하구"
    case seogu = "서구"
    case suyeong = "수영구"
    case yeonje = "연제구"
    case yeongdo = "영도구"
    case jung = "중구"
    case haeundae = "해운대구"
}

enum Daegu: String, CaseIterable {
    case none = "시/군/구"
    case gunwi = "군위군"
    case namgu = "남구"
    case dalseo = "달서구"
    case dalseong = "달성군"
    case donggu = "동구"
    case bukgu = "북구"
    case seogu = "서구"
    case suyeonggu = "수성구"
    case junggu = "중구"
}

enum Incheon: String, CaseIterable {
    case none = "시/군/구"
    case gyeyanggu = "계양구"
    case namdonggu = "남동구"
    case donggu = "동구"
    case michuholgu = "미추홀구"
    case bupyeonggu = "부평구"
    case seogu = "서구"
    case yeonsugu = "연수구"
    case ongjingun = "옹진군"
    case junggu = "중구" 
}

enum Gwangju: String, CaseIterable {
    case none = "시/군/구"
    case gwangsan = "광산구"
    case namgu = "남구"
    case donggu = "동구"
    case bukgu = "북구"
    case seogu = "서구"
}

enum Daejeon: String, CaseIterable {
    case none = "시/군/구"
    case daedukgu = "대덕구"
    case donggu = "동구"
    case seogu = "서구"
    case yuseonggu = "유성구"
    case junggu = "중구"
}

enum Ulsan: String, CaseIterable {
    case none = "시/군/구"
    case namgu = "남구"
    case donggu = "동구"
    case bukgu = "북구"
    case uljugun = "울주군"
    case junggu = "중구"
}

enum Sejong: String, CaseIterable {
    case none = "시/군/구"
    case sejong = "세종특별자치시"
}

enum Gyeonggi: String, CaseIterable {
    case none = "시/군/구"
    case gapyeonggun = "가평군"
    case goyangsiDeogyanggu = "고양시 덕양구"
    case goyangsiIlsandonggu = "고양시 일산동구"
    case goyangsiIlsanseogu = "고양시 일산서구"
    case gwacheonsi = "과천시"
    case gwangmyeongsi = "광명시"
    case gwangjusi = "광주시"
    case gurisi = "구리시"
    case gunposi = "군포시"
    case namnyangjusi = "남양주시"
    case dongducheonsi = "동두천시"
    case bucheonsi = "부천시"
    case seongnamsiBundanggu = "성남시 분당구"
    case seongnamsiSuji = "성남시 수정구"
    case seongnamsiJungwongu = "성남시 중원구"
    case suwonsiGwonseongu = "수원시 권선구"
    case suwonsiYeongtonggu = "수원시 영통구"
    case suwonsiJangan = "수원시 장안구"
    case suwonsiPadalgu = "수원시 팔달구"
    case siheungsi = "시흥시"
    case ansansiDanwongu = "안산시 단원구"
    case ansansiSangrokgu = "안산시 상록구"
    case anseongsi = "안성시"
    case anyangsiDongan = "안양시 동안구"
    case anyangsiManangu = "안양시 만안구"
    case yangjusi = "양주시"
    case yangpyeongyang = "양평군"
    case yeojusi = "여주시"
    case yeoncheongoon = "연천군"
    case osansi = "오산시"
    case yunginsiGihungu = "용인시 기흥구"
    case yunginsiSuji = "용인시 수지구"
    case yunginsiCheoin = "용인시 처인구"
    case uiwangsi = "의왕시"
    case uijeongbusi = "의정부시"
    case icheonsi = "이천시"
    case pajusi = "파주시"
    case pyeongtaksi = "평택시"
    case pocheonsi = "포천시"
    case hanamsi = "하남시"
    case hwaseongsi = "화성시"
}

enum Gangwon: String, CaseIterable {
    case sigungu = "시/군/구"
    case gangneungsi = "강릉시"
    case gosunggun = "고성군"
    case donghaesi = "동해시"
    case samcheoksi = "삼척시"
    case sokchosi = "속초시"
    case yanggugun = "양구군"
    case yangyanggun = "양양군"
    case yeongwolgun = "영월군"
    case wonjusi = "원주시"
    case injegun = "인제군"
    case jeongseongun = "정선군"
    case cheolwongun = "철원군"
    case chuncheonsi = "춘천시"
    case taebaeksi = "태백시"
    case pyeongchanggun = "평창군"
    case hongcheongun = "홍천군"
    case hwacheongun = "화천군"
    case hongsunggun = "횡성군"
}

enum Chungbuk: String, CaseIterable {
    case sigungu = "시/군/구"
    case goesangun = "괴산군"
    case danyanggun = "단양군"
    case boeungun = "보은군"
    case yeongdonggun = "영동군"
    case okcheongun = "옥천군"
    case eumseonggun = "음성군"
    case jecheonsi = "제천시"
    case jeungpyeonggun = "증평군"
    case jincheongun = "진천군"
    case cheongjusisangdanggu = "청주시 상당구"
    case cheongjusiseowongu = "청주시 서원구"
    case cheongjusicheongwongu = "청주시 청원구"
    case cheongjusiheungdeokgu = "청주시 흥덕구"
    case chungjusi = "충주시"
}

enum Chungnam: String, CaseIterable {
    case sigungu = "시/군/구"
    case gyeryongsi = "계룡시"
    case gongjusi = "공주시"
    case geumsangun = "금산군"
    case nonsansi = "논산시"
    case dangjinsi = "당진시"
    case boryeongsi = "보령시"
    case buyeogun = "부여군"
    case seosansi = "서산시"
    case seocheongun = "서천군"
    case asansi = "아산시"
    case yesangun = "예산군"
    case cheonansidongnamgu = "천안시 동남구"
    case cheonansiseobukgu = "천안시 서북구"
    case cheongyanggun = "청양군"
    case taeangun = "태안군"
    case hongseonggun = "홍성군"
}

enum Jeonbuk: String,CaseIterable {
    case sigungu = "시/군/구"
    case gochanggun = "고창군"
    case gunsansi = "군산시"
    case kimjesi = "김제시"
    case namwonsi = "남원시"
    case mujugun = "무주군"
    case buangun = "부안군"
    case sunchanggun = "순창군"
    case wanjugu = "완주군"
    case iksansi = "익산시"
    case imsilgun = "임실군"
    case jangsugun = "장수군"
    case jeonjusideokjingu = "전주시 덕진구"
    case jeonjusiwansangu = "전주시 완산구"
    case jeongeupsi = "정읍시"
    case jinangun = "진안군"
}

enum Jeonnam: String, CaseIterable {
    case sigungu = "시/군/구"
    case gangjingun = "강진군"
    case goheunggun = "고흥군"
    case gokseonggun = "곡성군"
    case gwangyangsi = "광양시"
    case guryegun = "구례군"
    case najusi = "나주시"
    case damyanggun = "담양군"
    case mokposi = "목포시"
    case muanGun = "무안군"
    case bosingGun = "보성군"
    case suncheonsi = "순천시"
    case sinanGun = "신안군"
    case yeosusi = "여수시"
    case yeonggwanggun = "영광군"
    case yeongamgun = "영암군"
    case wandogun = "완도군"
    case jangseonggun = "장성군"
    case jangheunggun = "장흥군"
    case jindogun = "진도군"
    case hampyeonggun = "함평군"
    case haenamgun = "해남군"
    case hwasoongun = "화순군"
}

enum Gyeongbuk: String, CaseIterable {
    case sigungu = "시/군/구"
    case gyeongsansi = "경산시"
    case gyeongjusi = "경주시"
    case goryeonggun = "고령군"
    case gumisi = "구미시"
    case gimcheonsi = "김천시"
    case mungyeongsi = "문경시"
    case bonghwagun = "봉화군"
    case sangjusi = "상주시"
    case seongjugun = "성주군"
    case andongsi = "안동시"
    case yeongdeokgun = "영덕군"
    case yeongyanggun = "영양군"
    case yeongjusi = "영주시"
    case yeongcheonsi = "영천시"
    case yecheongun = "예천군"
    case ulleunggun = "울릉군"
    case uljingun = "울진군"
    case uiseonggun = "의성군"
    case cheongdogun = "청도군"
    case cheongsongun = "청송군"
    case chilgokgun = "칠곡군"
    case pohangnamgu = "포항시 남구"
    case pohangbukgu = "포항시 북구"
}

enum Gyeongnam: String, CaseIterable {
    case sigungu = "시/군/구"
    case geojesi = "거제시"
    case geochanggun = "거창군"
    case gosunggun = "고성군"
    case gimhaesi = "김해시"
    case namhaegun = "남해군"
    case miryangsi = "밀양시"
    case sachunsi = "사천시"
    case sanchungun = "산청군"
    case yangsansi = "양산시"
    case uiryeonggun = "의령군"
    case jinjusi = "진주시"
    case changnyeonggun = "창녕군"
    case masanhappogu = "창원시 마산합포구"
    case masanhoewoingu = "창원시 마산회원구"
    case seongsangu = "창원시 성산구"
    case uichanggu = "창원시 의창구"
    case jinhaegu = "창원시 진해구"
    case tongyeongsi = "통영시"
    case hadonggun = "하동군"
    case hamangu = "함안군"
    case hamyanggun = "함양군"
    case hapcheongun = "합천군"
}

enum Jeju: String, CaseIterable {
    case sigungu = "시/군/구"
    case seogwiposi = "서귀포시"
    case jejusi = "제주시"
   // 나머지 시/군/구 추가
}
